gfunction start(){
    makePlanetOutline();
    makePlanetStripes();
}
function makePlanetOutline(){
    turnLeft();
    for (var i = 0; i < 12; i++) {
        move();
    }
    turnRight();
    for (var i = 0; i < 17; i++) {
        move();
    }
    for (var i = 0; i < 4; i++) {
        makePlanetFourth();
    }
}
function makePlanetFourth(){
    for (var i = 0; i < 6; i++) {
        paint(Color.cyan);
        move();
    }
    turnLeft();
    move();
    turnRight();
    for (var i = 0; i < 2; i++) {
        paint(Color.cyan);
        move();
    }
    turnLeft();
    move();
    paint(Color.cyan);
    move();
    turnRight();
    move();
    paint(Color.cyan);
    turnLeft();
    move();
    paint(Color.cyan);
    move();
    turnRight();
    move();
    turnLeft();
}
function makePlanetStripes(){
    turnLeft();
    move();
    turnRight();
    for (var i = 0; i < 3; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 3; i++) {
        paint(Color.blue);
        move();
    }
    move();
    turnLeft();
    move();
    turnLeft();
    for (var i = 0; i < 3; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 3; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    for (var i = 0; i < 6; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 6; i++) {
        paint(Color.purple);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    turnRight();
    move();
    turnRight();
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 6; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 2; i++) {
        paint(Color.purple);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 5; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 5; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    paint(Color.purple);
    move();
    for (var i = 0; i < 5; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 6; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 6; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    for (var i = 0; i < 5; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 8; i++) {
        paint(Color.blue);
        move();
    }
    paint(Color.purple);
    move();
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 7; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 5; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    move();
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 10; i++) {
        paint(Color.purple);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 8; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    move();
    for (var i = 0; i < 10; i++) {
        paint(Color.blue);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    move();
    for (var i = 0; i < 6; i++) {
        paint(Color.blue);
        move();
    }
}

New code
function start(){
       makePlanetOutline();
    makePlanetStripes();
}
function makePlanetOutline(){
    turnLeft();
    for (var i = 0; i < 12; i++) {
        move();
    }
    turnRight();
    for (var i = 0; i < 17; i++) {
        move();
    }
    for (var i = 0; i < 4; i++) {
        makePlanetFourth();
    }
}
function makePlanetFourth(){
    for (var i = 0; i < 6; i++) {
        paint(Color.cyan);
        move();
    }
    turnLeft();
    move();
    turnRight();
    for (var i = 0; i < 2; i++) {
        paint(Color.cyan);
        move();
    }
    turnLeft();
    move();
    paint(Color.cyan);
    move();
    turnRight();
    move();
    paint(Color.cyan);
    turnLeft();
    move();
    paint(Color.cyan);
    move();
    turnRight();
    move();
    turnLeft();
}
function makePlanetStripes(){
    turnLeft();
    move();
    turnRight();
    for (var i = 0; i < 3; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 3; i++) {
        paint(Color.blue);
        move();
    }
    move();
    turnLeft();
    move();
    turnLeft();
    for (var i = 0; i < 3; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 3; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    for (var i = 0; i < 6; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 6; i++) {
        paint(Color.purple);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    turnRight();
    move();
    turnRight();
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 6; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 2; i++) {
        paint(Color.purple);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 5; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 5; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    paint(Color.purple);
    move();
    for (var i = 0; i < 5; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 6; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 6; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.purple);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    for (var i = 0; i < 5; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 8; i++) {
        paint(Color.blue);
        move();
    }
    paint(Color.purple);
    move();
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 7; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 5; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    move();
    for (var i = 0; i < 2; i++) {
        paint(Color.blue);
        move();
    }
    for (var i = 0; i < 10; i++) {
        paint(Color.purple);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    for (var i = 0; i < 8; i++) {
        paint(Color.purple);
        move();
    }
    for (var i = 0; i < 4; i++) {
        paint(Color.blue);
        move();
    }
    turnRight();
    move();
    turnRight();
    move();
    move();
    for (var i = 0; i < 10; i++) {
        paint(Color.blue);
        move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    move();
    for (var i = 0; i < 6; i++) {
        paint(Color.blue);
        move();
    }
    goHome1();
    function goHome1(){
        if (facingWest()) {
            while (frontIsClear()) {
                move();
            }
            turnLeft();
            while (frontIsClear()) {
                move();
            }
            turnLeft();
        }
    }
    for (var i = 0; i < 19; i++) {
        paintWorld();
        goBack();
        paintWorld();
        backUp();
    }
    paintWorld();
    goBack();
    paintWorld();
    goHome();
    makeStars();
    function goHome(){
        if (facingWest()) {
            turnLeft();
            while (frontIsClear()) {
                move();
            }
            turnLeft();
        }
    }
}
function paintWorld(){
    while (colorIs(Color.white)) {
        paint(Color.black);
        move();
        if (frontIsBlocked()) {
            paint(Color.black);
            turnLeft();
            move();
            turnLeft();
        }
        if (colorIs(Color.cyan)) {
            while (colorIs(Color.cyan)) {
                colorCheck();
            }
        }
        if (colorIs(Color.purple)) {
            while (colorIs(Color.purple)) {
                colorCheck();
            }
        }
        if (colorIs(Color.blue)) {
            while (colorIs(Color.blue)) {
                colorCheck();
            }
        }
    }
}
function goBack(){
    turnLeft();
    move();
    turnLeft();
}
function colorCheck(){
    while (frontIsClear()) {
        move();
        if (colorIs(Color.white)) {
            paint(Color.black);
        }
    }
}
function backUp(){
    turnLeft();
    turnLeft();
    turnLeft();
    move();
    turnRight();
}
function makeStars(){
    for (var i = 0; i < 2; i++) {
        while (frontIsClear()) {
            move();
        }
        goBack();
        while (frontIsClear()) {
            move();
        }
        backUp();
    }
    for (var i = 0; i < 31; i++) {
        move();
    }
    makeCyanStar();
    function makeCyanStar(){
        paint(Color.cyan);
        turnLeft();
        move();
        paint(Color.cyan);
        turnLeft();
        turnLeft();
        move();
        turnRight();
        move();
        paint(Color.cyan);
        turnRight();
        turnRight();
        move();
        turnRight();
        move();
        paint(Color.cyan);
        turnLeft();
        turnLeft();
        move();
        turnRight();
        move();
        paint(Color.cyan);
        turnLeft();
        turnLeft();
        move();
        turnLeft();
        turnLeft();
    }
    for (var i = 0; i < 2; i++) {
        while (frontIsClear()) {
            move();
        }
        goBack();
        while (frontIsClear()) {
            move();
        }
        backUp();
    }
    for (var i = 0; i < 6; i++) {
        move();
    }
    makeWhiteStar();
    function makeWhiteStar(){
        paint(Color.white);
        turnLeft();
        move();
        paint(Color.white);
        turnLeft();
        turnLeft();
        move();
        turnRight();
        move();
        paint(Color.white);
        turnRight();
        turnRight();
        move();
        turnRight();
        move();
        paint(Color.white);
        turnLeft();
        turnLeft();
        move();
        turnRight();
        move();
        paint(Color.white);
        turnLeft();
        turnLeft();
        move();
        turnLeft();
        turnLeft();
    }
    for (var i = 0; i < 4; i++) {
        while (frontIsClear()) {
            move();
        }
        goBack();
        while (frontIsClear()) {
            move();
        }
        backUp();
    }
    for (var i = 0; i < 35; i++) {
        move();
    }
    makeWhiteStar();
    for (var i = 0; i < 2; i++) {
        while (frontIsClear()) {
            move();
        }
        goBack();
        while (frontIsClear()) {
            move();
        }
        backUp();
    }
    for (var i = 0; i < 3; i++) {
        move();
    }
    makeCyanStar();
    for (var i = 0; i < 6; i++) {
        while (frontIsClear()) {
            move();
        }
        goBack();
        while (frontIsClear()) {
            move();
        }
        backUp();
    }
    for (var i = 0; i < 29; i++) {
        move();
    }
    makeCyanStar();
    for (var i = 0; i < 2; i++) {
        while (frontIsClear()) {
            move();
        }
        goBack();
        while (frontIsClear()) {
            move();
        }
        backUp();
    }
    for (var i = 0; i < 11; i++) {
        move();
    }
    makeWhiteStar();
}
